[pyprland]
plugins = [
	"scratchpads",
	"workspaces_follow_focus"
]

# [workspaces_follow_focus]
# max_workspaces = 9

[scratchpads.term]
command = "kitty --class kitty-scratch"
class="kitty-scratch"
animation = "fromBottom"
size = "60% 60%"
margin = "18%"
unfocus = "hide"

[scratchpads.music]
command = "spotify"
animation = "fromBottom"
size = "80% 80%"
margin = "8%"
unfocus = "hide"

[scratchpads.volume]
animation = "fromBottom"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "60% 60%"
margin = "18%"
unfocus = "hide"
lazy = true

# [monitors]
# unknown = "wlrlui"

# [monitors.placement]
# "Acer".leftOf = "HDMI-0"
# "Sony".topOf = "eDP-1"
