## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░
## CROSS-SHELL PROMPT
## The minimal, blazing-fast, and infinitely customizable prompt for any shell!

# format = """
# $hostname\
# $directory\
#
# $localip\
# $shlvl\
# $singularity\
# $kubernetes\
# $vcsh\
# $hg_branch\
# $docker_context\
# $package\
# $custom\
#
# $sudo\
#
# $fill\
# $git_branch\
# $git_status\
# $git_commit\
# $cmd_duration\
# $jobs\
# $battery\
# $time\
# $status\
# $os\
# $container\
# $character
# $shell
# """

format = "$directory$character$shell"
right_format = "$git_branch$git_status"

# Disable the blank line at the start of the prompt
add_newline = false

# Second param
[hostname]
ssh_only = true 
format = "[](fg:#101319 bg:none)[█](fg:#f4f3ee bg:#101319)[$ssh_symbol$hostname](bold bg:#f4f3ee)[](fg:#f4f3ee bg:none) "
disabled = false

# Third param
[directory]
format = "[  ](fg:#5599e2 bg:none)[$path]($style) "
# format = "[$path]($style)[ ](fg:#101319 bg:#101319)[](fg:#5599e2 bg:#101319)[ ](fg:#101319 bg:#5599e2)[](fg:#5599e2 bg:none)"
style = "fg:#f4f3ee bg:none bold"
truncation_length = 3
truncate_to_repo=false
read_only = " "

## SECOND LINE/ROW: Prompt
# Prompt: param 2 └─
[character]
success_symbol = "[](#5599e2)"
error_symbol = "[](#e34f4f)"
vimcmd_symbol = "[](#7cc47c)" 

[line_break]
disabled = true

[fill]
symbol = ' '
style = 'bold green'

[cmd_duration]
min_time = 1
format = "[](fg:#101319 bg:none)[$duration]($style)[](fg:#101319 bg:#101319)[](fg:#956dca bg:#101319)[󱑂 ](fg:#101319 bg:#956dca)[](fg:#956dca bg:none)"
disabled = false
style = "fg:#f4f3ee bg:#101319 bold"


[git_branch]
format = "[$symbol$branch](fg:#f4f3ee bg:none) "
symbol = " "

[git_status]
format="$all_status$ahead_behind "
style = "fg:#F4F3EE bg:#101319"
conflicted = "="
ahead =	"[⇡${count}](fg:#7CC47C bg:none)"
behind = "[⇣${count}](fg:#E34F4F bg:none)"
diverged = "⇡${ahead_count}⇣${behind_count}"
untracked = "[?${count}](fg:#5599E2 bg:none)"
stashed = "*"
modified = "[!${count}](fg:#ff9e64)"
staged = "[+${count}](fg:#7CC47C bg:none)"
renamed = "[~${count}](fg:#5599E2 bg:none)"
deleted = "[-${count}](fg:#E34F4F bg:none)"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

# # SYMBOLS

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

# [directory]

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[haskell]
symbol = "λ "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[nodejs]
format = "via [ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true
