[global/wm]
include-file = colors.ini
include-file = modules.ini

[bar/bar]
width = 100%
height = 22pt
radius = 10

dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt
border-size = 12

padding-left = 1.5
padding-right = 2

module-margin = 1

separator = ""
separator-foreground = ${colors.buffer}

font-0 = JetBrainsMono:size=9
font-1 = DejaVu Sans Mono wifi ramp:size=9
font-2 = FontAwesome:size=9

; xwindow
modules-left = xworkspaces
modules-center = date
modules-right = xkeyboard pulseaudio network battery launcher

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; tray-position = right
 
; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

override-redirect = true
